sudo: required
dist: trusty
language: node_js
node_js:
  - 8.2.1
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libkrb5-dev
      - xvfb
      - libgtk2.0-0
      - libgconf-2-4
      - libasound2
      - libxtst6
      - libxss1
      - libnss3
-before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> .npmrc
script: npm run ci
cache:
  directories:
    - $HOME/.electron
