sudo: required
dist: trusty
language: node_js
node_js:
  - 8.2.1
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libkrb5-dev
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> .npmrc
script: npm run ci
cache:
  directories:
    - $HOME/.electron
    - node_modules
